# Generated by Django 2.1.3 on 2018-11-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Komik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'komik',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('list_size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.Account')),
            ],
            options={
                'db_table': 'list',
            },
        ),
        migrations.CreateModel(
            name='Listrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('komik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.Komik')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.List')),
            ],
            options={
                'db_table': 'listrank',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('komik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.Komik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.Account')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.Komik')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='komikrepo.Tag')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('tag', 'komik')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('komik', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='listrank',
            unique_together={('list', 'ranking')},
        ),
    ]
