# Generated by Django 2.1.3 on 2018-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komikrepo', '0004_auto_20181113_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komik',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
