# Generated by Django 2.1.3 on 2018-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komikrepo', '0005_auto_20181113_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='komik',
            name='komik_tags',
            field=models.ManyToManyField(through='komikrepo.Tags', to='komikrepo.Tag'),
        ),
    ]
