# Generated by Django 2.1.3 on 2018-11-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komikrepo', '0007_auto_20181125_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_komiks',
            field=models.ManyToManyField(through='komikrepo.ListRank', to='komikrepo.Komik'),
        ),
        migrations.AlterUniqueTogether(
            name='listrank',
            unique_together={('list', 'ranking'), ('list', 'komik')},
        ),
    ]
